### ISSUE TITLE
KQ330 - spec

### ISSUE THREAD

**Issue by Cloolalang** [santoshkrishnanr/KQ330-power-line-communication-#1]
Mysterious black box..whats inside?

So I monitor mine with an AM radio nearby, you can hear the morse-code like speed of the communication of these units, im thinking mine are at about 50b with mains AC.
p

**Comment by santoshkrishnanr** [comment]
Hi, cloolalang,
Even I had the same doubt, in the beginning.I just understood the basic and i assume, thats the main controller where the FSK (Frequency shift keeying) happens which you heard. feel free to correct me if i am wrong   :)

**Comment by Cloolalang** [comment]
> 
> 
> Hi, cloolalang,
> Even I had the same doubt, in the beginning.I just understood the basic and i assume, thats the main controller where the FSK (Frequency shift keeying) happens which you heard. feel free to correct me if i am wrong :)

I gave up using these units in my project in favor of radio based devices.
Reasons:
1) Comms too slow.
2) Limited by noise interference on power lines
3) ISM-band Radio is cheap, well-supported and much faster:
Lora peer-peer (Mysensors)
Ebyte uart radios
radioshuttle

**Comment by santoshkrishnanr** [comment]
yes completely agree, I had to use many filters to get the actual data. 
all the best for your project.
