### ISSUE TITLE
Maximum distance transmission

### ISSUE THREAD

**Issue by manhtran98bg** [santoshkrishnanr/KQ330-power-line-communication-#2]
Hi, i am doing an project that " Detect Phase of Power line using KQ330F module".
So i want to ask you What maximum distance This module can transmission? Please helping me! Thank you so much!
"Sorry my English is not good"

**Comment by santoshkrishnanr** [comment]
Hi manhtran98bg Nǐ hǎo,
as per internet and technical specification, I heard Transmission distance up to 2.5Km (in power line).
but practically testing I was able to get information till the next room (approx 500m).
but will be happy if you tested more than that.
Xièxiè

**Comment by Cloolalang** [comment]
I got 50m through apartment wiring 5th floor to garage on same AC phase.
It only worked if I do following
1) use one AC plug socket for KQ330  only, do not plug anything else into same socket
2) Keep away from noise sources: switch-power power supplies, florescent lamps, motors etc
3) Use AM radio to monitor the KQ330 during testing
4) Baud rate is around 100b with 50Hz AC power on the same line, I could not get them to work without AC power on the line
5) Dont feed in too much uart data too quickly, it will overload buffers
6) KQ330 listen all the time but transmits when there is UART data, (half-duplex comms)
7) 9600 8N1 UART input and output, only send small amounts of data at a time... my 25 bytes takes 6000ms!
8) Make sure you give the KQ-330 a good clean DC power supply of 600mA minimum on both power pins
9) Frequency is 132KHZ FSK modulation, built-in error correction. somehow synchronized to zero-cross of AC
10) !!!!!!!!!!!!!!!!TAKE GREAT CARE WORKING WITH AC LINE VOLTAGES!!!!! 
11) Make sure your devices are on the same AC phase wiring for both signal coupling and FSK timing
12) I tested swapping the connection L-N, N-L, L-E, N-E only really works well L-N
13) Fit a fuse on the AC line for extra safety

Good luck, 
I had better luck and range with Radios HC12 etc.
